### PR TITLE
Fix uint to format in decimal

### LINKED ISSUE #185: print uint's in decimal?
Hello. Great library! I enjoy using it in my unit tests.
Just one request:
This program:
```
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
)

func main() {
	fmt.Println(cmp.Diff(uint32(42), uint32(4)))
}
```

prints:
```
  uint32(
- 	0x2a,
+ 	0x04,
  )
```

this is hard to understand for humans. It would be nice if there was a mode to print these numbers in decimal form.

### PR DESCRIPTION
**Pull request by 178inaba**
Since byte is an alias for uint8, format it in hex.

Fixes #185.

### CODE REVIEW

**Comment by dsnet** [comment]
Thanks for the PR. I feel like we should always use decimal except for `[]uint8`. This is different from what this PR does, which is to just special-case `uint8` by itself.

**Comment by 178inaba** [comment]
@dsnet Thanks for the review!
I found the case of `isBinary`.
https://github.com/google/go-cmp/blob/049b73f65ccf77e9b278cef9beb6a20a9f55f8e7/cmp/report_slices.go#L132-L147

This seems to be the case when it is `[]byte` and not unicode.
https://github.com/google/go-cmp/blob/049b73f65ccf77e9b278cef9beb6a20a9f55f8e7/cmp/report_slices.go#L73
https://github.com/google/go-cmp/blob/049b73f65ccf77e9b278cef9beb6a20a9f55f8e7/cmp/report_slices.go#L87

Should I format in hex only for `isBinary` and `uintptr`?

**Comment by 178inaba** [comment]
@dsnet Hello!
I wrote the code to format only []uint8 type in hex.
Would you please review this pull request again?

File: cmp/report_compare.go [hunk 1]
```diff
@@ -81,14 +81,20 @@ func (opts formatOptions) FormatDiff(v *valueNode) textNode {
 		return opts.FormatDiffSlice(v)
 	}
 
+	var isSlice bool
+	if v.parent != nil &&
```
Comment (dsnet) [inline cmp/report_compare.go:85]: (Stye-nit): Keep conditional as single line.

File: cmp/report_compare.go [hunk 2]
```diff
@@ -81,14 +81,20 @@ func (opts formatOptions) FormatDiff(v *valueNode) textNode {
 		return opts.FormatDiffSlice(v)
 	}
 
+	var isSlice bool
```
Comment (dsnet) [inline cmp/report_compare.go:84]: Perhaps call this `withinSlice` instead (here and elsewhere)? Since we're usually looking at this variable from the perspective of the child.

**Comment by 178inaba** [comment]
@dsnet Thank you for the review!
I fixed it!

**Comment by dsnet** [comment]
Thanks!

**Comment by dsnet** [comment]
Ooops. Forgot to merge it.
